Es and fr book
nushell/nushell.github.io pull request #1697
Opened 2024-12-22 16:05 UTC by 0x4D5352

Split out Spanish and French for #1684. Didn't appear to have any of the same indentation issues but I could be a bit tab-blind after all this, lol.

2024-12-22 22:15 UTC, NotTheDr01ds requested changes
Thanks! A few more minor tweaks.

I'm also finding out just how outdated some of these translations are - Apparently the Spanish one still includes an `add` command example, which was renamed to `insert` in 2019 apparently!

2024-12-22 22:15 UTC, NotTheDr01ds commented on es/book/trabajando_con_tablas.md
> +# /home/sophia/Source/nushell(master)
```suggestion
```

Leftover prompt line

2024-12-22 22:15 UTC, NotTheDr01ds commented on fr/book/cheat_sheet.md
> +# => hello world!
```suggestion
use greetings.nu
greetings
# => greetings and salutations!
greetings hello world
# => hello world!
```

2024-12-22 23:14 UTC, 0x4D5352 commented on es/book/instalacion.md
>   C:\Users\user>
Yeah, I wasn't quite sure whether or not to keep those in but they don't seem super relevant.

2024-12-31 22:56 UTC, NotTheDr01ds commented on es/book/entorno.md
> +# => MI_VARIABLE=VALOR echo $nu.env.MI_VARIABLE
Looks like this one slipped through:

```suggestion
MI_VARIABLE=VALOR echo $nu.env.MI_VARIABLE
```

2024-12-31 22:57 UTC, NotTheDr01ds commented on es/book/instalacion.md
> +# ./nushell
Probably not necessary here - I'd probably just remove this one.

2024-12-31 23:06 UTC, NotTheDr01ds requested changes
Thank you again, and apologies for not getting the reviews on these done sooner.  Just a few things on this one and it will be ready.

2024-12-31 23:06 UTC, NotTheDr01ds commented on fr/book/cheat_sheet.md
> +# => [1 2 3] | each { $x += 1 }
```suggestion
[1 2 3] | each { $x += 1 }
```

2024-12-31 23:27 UTC, NotTheDr01ds commented on es/book/instalacion.md
> +# ./nushell
```suggestion
```

2024-12-31 23:29 UTC, NotTheDr01ds commented on es/book/instalacion.md
> +# ./nushell
```suggestion
```

2024-12-31 23:29 UTC, NotTheDr01ds commented on es/book/instalacion.md
> +# ./nushell
```suggestion
```

2024-12-31 23:31 UTC, NotTheDr01ds approved these changes

2024-12-31 23:32 UTC, merged